##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [4]:
import numpy as np

array = np.array([1,2,3,4,5,6],dtype="int")

print(f"Arrayin tipi : {array.dtype}\nArrayin boyutu : {array.ndim}\nArrayin eleman sayisi : {array.shape}")

Arrayin tipi : int32
Arrayin boyutu : 1
Arrayin eleman sayisi : (6,)


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [12]:
iki_boyutlu_array = np.array([[1,2,6,7],[4,3,9,5]])
uc_boyutlu_array = np.array([
    [
        [7,5,14],[21,8,11]
    ]
    ,
    [
        [8,6,20],[14,3,9]
    ]
    ])


print(f"Array boyut kontrolu 2 boyutlu : {iki_boyutlu_array.ndim}")
print(f"Array boyut kontrolu 3 boyutlu : {uc_boyutlu_array.ndim}")

Array boyut kontrolu 2 boyutlu : 2
Array boyut kontrolu 3 boyutlu : 3


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [13]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
iki_boyutlu_array[0,1]

2

In [14]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
iki_boyutlu_array[0,3]

7

In [15]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
uc_boyutlu_array[1,1,2]

9

In [16]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
uc_boyutlu_array[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [19]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
iki_boyutlu_array[0,1:3]


array([2, 6])

In [21]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
iki_boyutlu_array[1,1:4]

array([3, 9, 5])

In [22]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
uc_boyutlu_array[0,1:4]

array([[21,  8, 11]])

In [28]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
uc_boyutlu_array[1,0,1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [53]:
sifirlar = np.zeros((5,3),dtype="int")
birler = np.ones((5,3),dtype="int")

print(f"Sifirlardan olusan array : \n{sifirlar}\n\nBirlerden olusan array : \n{birler}")


Sifirlardan olusan array : 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Birlerden olusan array : 
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [54]:
satir_birlestirmesi = np.concatenate([sifirlar,birler])
print(f"Satirlarin birlestirildigi durum : \n{satir_birlestirmesi}\n")

sutun_birlestirmesi = np.concatenate([sifirlar,birler],axis=1)
print(f"Sutunlarin birlestirildigi durum : \n{sutun_birlestirmesi}\n")

Satirlarin birlestirildigi durum : 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sutunlarin birlestirildigi durum : 
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]

